<?php require __DIR__.'/header.php'; ?>
<section class="hero"><div class="container"><span class="eyebrow">US FLIGHT TIME INFORMATION</span><h1>Flight Times, Flight Duration &amp; Air Distance</h1><p class="lead">Estimate how long it takes to fly between U.S. cities and compare air travel with driving, bus, train, walking and bicycle travel.</p>
<form class="search-card" onsubmit="return goToRoute()"><div class="field"><label for="from">From</label><input id="from" list="cities" placeholder="New York, NY"></div><div class="swap">→</div><div class="field"><label for="to">To</label><input id="to" list="cities" placeholder="Los Angeles, CA"></div><button type="submit">Calculate Flight Time</button>
<datalist id="cities"><?php foreach($cities as $c): ?><option value="<?=e($c['name'])?>"></option><?php endforeach; ?></datalist></form><div id="form-error" class="form-error"></div></div></section>
<section class="container content-grid"><div><h2>How Flight Time Is Estimated</h2><p>Flight duration estimates use the approximate air distance between city coordinates and a configurable average cruising speed, plus a small operational allowance.</p><p>Actual flight times vary with aircraft type, routing, wind, air traffic, airport procedures and operating conditions.</p></div><aside class="info-card"><h3>Travel information</h3><ul><li>Estimated flight time</li><li>Air distance</li><li>Driving time and fuel estimate</li><li>Bus and train estimates</li><li>Walking and bicycle estimates</li></ul></aside></section>
<section class="container"><h2>Popular Flight Time Routes</h2><div class="route-grid"><?php $pairs=[['new-york-ny','los-angeles-ca'],['new-york-ny','miami-fl'],['chicago-il','los-angeles-ca'],['dallas-tx','new-york-ny'],['seattle-wa','los-angeles-ca'],['atlanta-ga','new-york-ny'],['boston-ma','san-francisco-ca'],['denver-co','chicago-il'],['houston-tx','miami-fl'],['las-vegas-nv','new-york-ny'],['orlando-fl','chicago-il'],['phoenix-az','seattle-wa']]; foreach($pairs as $p): $a=find_city($p[0],$cities);$b=find_city($p[1],$cities);if(!$a||!$b)continue; ?><a class="route-card" href="/flight-time/<?=$a['slug']?>-to-<?=$b['slug']?>"><strong><?=e($a['name'])?> → <?=e($b['name'])?></strong><span>View estimated flight time</span></a><?php endforeach; ?></div></section>
<section class="container faq"><h2>Flight Time FAQ</h2><details><summary>What is flight time?</summary><p>Flight time is an estimated duration of air travel between two locations. It is different from airport check-in and other ground time.</p></details><details><summary>Are the flight times exact?</summary><p>No. They are modeled estimates and actual duration can vary by aircraft, route, weather and operations.</p></details><details><summary>Does flight time include airport time?</summary><p>No. Check-in, security, boarding, baggage claim and airport transfers are separate.</p></details></section>
<script>
const cityMap=<?=json_encode(array_column($cities,'slug','name'),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?>;
function goToRoute(){const a=document.getElementById('from').value.trim(),b=document.getElementById('to').value.trim(),e=document.getElementById('form-error');if(!cityMap[a]||!cityMap[b]){e.textContent='Please select both cities from the available list.';return false}if(cityMap[a]===cityMap[b]){e.textContent='Please choose two different cities.';return false}location.href='/flight-time/'+cityMap[a]+'-to-'+cityMap[b];return false}
</script><?php require __DIR__.'/footer.php'; ?>